import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/lib/actions/AuthProvider";
import ThemesProvider from "../components/themes/ThemesProvider";
import ToastProvider from "../components/ToastProvider";
import TopNavbar from "../components/navbars/TopNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <ThemesProvider>
            <ToastProvider/>
            <div className="flex flex-col gap-1">
              <TopNavbar/>
              <div className="w-full container mx-auto my-10">
            {children}
          </div>
            </div>
              
        </ThemesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
